main: com.Moshu.SimpleAdReloaded.Main
version: 1.8
name: SimpleAdvertising-Reloaded
author: Moshu
softdepend: [PlayerPoints, PermissionsEx]
depend: [Vault, Essentials]

commands:
  ad:
    description: Make an ad on the chat.
  date:
    description: Allows you to see the time
  adb:
    description: Send server broadcast
  adp:
    description: Make ad using points
  news:
    description: See the news on the server
  msg:
    description: Message to a player
permissions:
  simplead.*:
    default: op
    description: Give players with op everything by default
  simplead.reload:
    default: op
  simplead.datecheck:
    default: true
  simplead.bc:
    default: op
  simplead.ad:
    default: true
  simplead.help:
    default: true
  simplead.msg:
    default: true
  simplead.news:
    default: true

#Made by Moshu with help from MosLaDatorie.
# Version 1.7
