main: com.SimpleAd.MoshuAd.Ad
version: 1.7
name: SimpleAdvertising
author: Moshu
softdepend: [PlaceholderAPI, PlayerPoints, PermissionsEx]
depend: [Vault, Essentials]

commands:
  ad:
    description: Make an ad on the chat.
  date:
    description: Allows you to see the time
  adb:
    description: Send server broadcast
  adt:
    description: Send title to all players
  adp:
    description: Make ad using points
permissions:
  simplead.*:
    default: op
    description: Give players with op everything by default
  simplead.reload:
    default: op
  simplead.datecheck:
    default: op
  simplead.adt:
    default: op
  simplead.bc:
    default: op
  simplead.ad:
    default: op
  simplead.help:
    default: op

#Made by Moshu with help from MosLaDatorie.
# Version 1.7
